export const defaultKPIConfig = [
  {
    id: 'apiResponseTime',
    label: 'Temps de réponse API',
    isVisible: true,
    threshold: 100,
    visualizationType: 'counter',
  },
  {
    id: 'cpuUsage',
    label: 'CPU',
    isVisible: true,
    threshold: 80,
    visualizationType: 'gauge',
  },
  {
    id: 'memoryUsage',
    label: 'Mémoire',
    isVisible: true,
    threshold: 90,
    visualizationType: 'gauge',
    notifyChannel: 'ntfy.sh',
  },
  {
    id: 'redisLatency',
    label: 'Latence Redis',
    isVisible: true,
    threshold: 100,
    visualizationType: 'chart',
    notifyChannel: 'ntfy.sh',
  },
  {
    id: 'bandwidth',
    label: 'Bande passante',
    isVisible: true,
    threshold: 1000,
    visualizationType: 'counter',
    notifyChannel: 'ntfy.sh',
  },
  {
    id: 'streamCount',
    label: 'Streams',
    isVisible: true,
    threshold: 1000,
    visualizationType: 'counter',
    notifyChannel: 'ntfy.sh',
  },
  {
    id: 'activeUsers',
    label: 'Utilisateurs actifs',
    isVisible: true,
    threshold: 500,
    visualizationType: 'counter',
    notifyChannel: 'ntfy.sh',
  },
  {
    id: 'storageUsed',
    label: 'Stockage utilisé',
    isVisible: true,
    threshold: 90,
    visualizationType: 'gauge',
    notifyChannel: 'ntfy.sh',
  },
  {
    id: 'requestSuccessRate',
    label: 'Taux de succès',
    isVisible: true,
    threshold: 95,
    visualizationType: 'gauge',
    notifyChannel: 'ntfy.sh',
  },
  {
    id: 'mediaProcessingTime',
    label: 'Temps de traitement',
    isVisible: true,
    threshold: 30,
    visualizationType: 'chart',
    notifyChannel: 'ntfy.sh',
  },
];
